packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  # Auth
  "@better-auth/expo": ^1.2.9
  "better-auth": ^1.2.9

  "tamagui": ^1.130.8

  # Dev tooling
  eslint: ^9.28.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.17
  tailwind-merge: ^3.3.0
  typescript: ^5.8.3
  zod: ^3.25.49
  "@tanstack/react-query": ^5.80.2
  "@trpc/client": ^11.2.0
  "@trpc/tanstack-react-query": ^11.2.0
  "@trpc/server": ^11.2.0
catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.1.6
    "@types/react-dom": ^19.1.5
#     react-native-renderer: 19.0.0

# overrides:
#   react-native-renderer: 19.0.0
# @check if still needed
onlyBuiltDependencies:
  - esbuild
patchedDependencies:
  better-auth: patches/better-auth.patch
